FROM python AS base

RUN mkdir /setup
WORKDIR /setup

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

ENV FLASK_APP app.py
WORKDIR /app

COPY . .

EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0" ]